# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Сложность',
                'verbose_name_plural': 'Сложности',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.CharField(max_length=256)),
                ('products', models.CharField(max_length=256)),
                ('conditions', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('materials_trans', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('products_trans', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.DifficultyLevel')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
    ]
