# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultylevel',
            name='variable',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
