# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_difficultylevel_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='variable',
            field=models.CharField(max_length=32),
        ),
    ]
